# Generated by Django 4.1.5 on 2023-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogi', '0002_postaus_luotu'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaus',
            name='kuva',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
